[env]
TERM = "screen-256color"
TERM_PROGRAM = "Alacritty"

[font]
size = 16.5

[window]
opacity = 1
decorations = "none"
dynamic_padding = true
option_as_alt = "Both"

[general]
import = [
    "~/.config/alacritty/themes/themes/ayu_light.toml"
]

[window.padding]
x = 0
y = 0

[font.normal]
family = "IosevkaTerm Nerd Font Mono"
style = "Light"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Equals"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "NumpadAdd"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "NumpadSubtract"
mods = "Command"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Command"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Command"

[[keyboard.bindings]]
action = "Hide"
key = "H"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "Q"
mods = "Command"

[[keyboard.bindings]]
action = "Quit"
key = "W"
mods = "Command"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "F"
mods = "Command|Control"

[[keyboard.bindings]]
action = "None"
key = "F"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "A"
mods = "Command"

[[keyboard.bindings]]
action = "None"
key = "B"
mode = "~Search"
mods = "Command"

[[keyboard.bindings]]
key = "Return"
mods = "Command"
action = "ToggleFullscreen"

